### PR TITLE
Add mix upload

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Comment by fhunleth** [comment]
The `nerves-keyboard` group recently added a `mix upload` alias to run `./upload.sh`. This is an attempt to remove the shell script part and make it a proper mix task.

It has the following issues:

1. Interacting with `ssh` isn't possible so passwords and encrypted ssh keys don't work. The ssh-agent can be used to get around this issue.
2. It creates zombie ssh processes if you CTRL-C
3. It appears to hang indefinitely when `nerves.local` isn't resolvable. Not sure why `ssh` doesn't exit, but it doesn't.

**Comment by jjcarstens** [comment]
You might be able to get past 3 if you `-o ConnectTimeout=3`

**Comment by fhunleth** [comment]
Thanks! The `ConnectTimeout` fixes number 3 and I think that I can no longer create zombie processes.

**Comment by fhunleth** [comment]
I updated the PR. Here's what happens:

```
root@nerves.local: Permission denied (publickey,keyboard-interactive,password).
** (Mix) Unexpected exit from ssh (:epipe)

This is known to happen when ssh interactively prompts you for a
passphrase. The following are workarounds:

1. Use the ssh-agent to hold your credentials.

2. Use the `upload.sh` script. Create one by running
   `mix firmware.gen.script`.
```

**Comment by fhunleth** [comment]
I feel like this is good enough to merge, so I'm going to do that and then create a PR for `nerves_firmware_ssh` that's similar.

**Pull request merged**
